# Generated by Django 5.2.8 on 2026-03-10 15:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event_image'),
        ),
    ]
